spring:
  datasource:
    url: "jdbc:h2:mem:store;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    platform: h2
    driver-class-name: "org.h2.Driver"
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      path: /admin/h2-console
      enabled: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging:
  level:
    ort.springframework.web: DEBUG
    org.springframework.ws.client.MessageTracing: INFO
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG
    org.springframework.hibernate: DEBUG


# ERRORS
error:
  whitelabel:
    enabled: true

